build_defaults: &build_defaults
  docker:
    - image: circleci/node:10-stretch
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  environment:
    STAGE: local
    SERVICE_NAME: swashbuckler-site
    REGISTRY_URL: 158277438783.dkr.ecr.us-east-1.amazonaws.com/swashbuckler-site

version: 2
jobs:
  build:
    <<: *build_defaults
    steps:
      - checkout
      - run:
          name: Add node_modules/bin to PATH
          command: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            ~/.cache/yarn
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build
          command: CI=false yarn build
      # - run:
      #     name: Lint
      #     command: yarn run lint
      # - run:
      #     name: Test
      #     command: yarn test
      # - run:
      #     name: Security check for npm packages
      #     command: nsp check
      - setup_remote_docker
      - deploy:
          name: Deploy to prod
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ECS_TOKEN=$(yarn --silent get-ecr-token)
              docker login -u AWS -p $ECS_TOKEN https://158277438783.dkr.ecr.us-east-1.amazonaws.com
              docker build -t $REGISTRY_URL:$CIRCLE_SHA1 .
              docker build -t $REGISTRY_URL:prod .
              docker push $REGISTRY_URL:$CIRCLE_SHA1
              docker push $REGISTRY_URL:prod
              yarn redeploy --stage prod --serviceName $SERVICE_NAME
            fi
workflows:
  version: 2
  build_test_deploy:
      jobs:
        - build:
            context: buccaneer